# Jekyll configuration
repository: shubham-11700069/Full-Stack-Development/audioplayer
theme: jekyll-theme-cayman
timezone: Europe/Berlin
name: "Audio Player"
title: "Audio Player"
description: "Audio Player for Nextcloud and ownCloud"
url: "https://rello.github.io/audioplayer"
author: "Shubham"
